version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn app:app --bind 0.0.0.0:8000
    volumes:
      - ./app/static:/home/app/static
    expose:
      - 8000
    env_file:
      - ./env.dev

  nginx:
    build: ./nginx
    volumes:
      - ./app/static:/home/app/static
    ports:
      - 8000:80
    depends_on:
      - app
